version: '3.7'
services:
  helmos:
    image: helmos
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER: docker
    volumes:
      - ./examples/charts/demo:/home/docker/chart