---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: default
rules:
- apiGroups: [ "" ]
  resources: [ "pods", "services"]
  verbs: [ "get", "list", "watch"]
- apiGroups: [ "extensions" ]
  resources: [ "deployments" ]
  verbs: [ "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-pod-reader
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
---

apiVersion: v1
kind: Pod
metadata:
  name: helmos
  namespace: default
spec:
  containers:
  - name: helmos
    image: maord/helmos
    volumeMounts:
        - name: chart
          mountPath: /home/docker/chart/Chart.yaml
          subPath: Chart.yaml
        - name: chart
          mountPath: /home/docker/chart/values.yaml
          subPath: values.yaml
        - name: chart
          mountPath: /home/docker/chart/requirements.yaml
          subPath: requirements.yaml
  volumes:
    - name: chart
      configMap:
        name: helmos
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: helmos
  namespace: default
data:
  Chart.yaml: |
    apiVersion: v1
    appVersion: "1.0"
    description: A Helm chart for Kubernetes
    name: demo
    version: 0.1.0
  values.yaml: ''
  requirements.yaml: |
    dependencies: 
    - name: 'mongodb-replicaset'
      version: '3.10.1'
      repository: '@stable'  
  

